// Auto generated by build.sh at Thu Jan 23 19:24:09 UTC 2014

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("1.1.0.1424")]
[assembly: AssemblyFileVersion("1.1.0.1424")]
[assembly: AssemblyInformationalVersion("See https://github.com/versionone/Platform.V1.ServerConnector/wiki")]

[assembly: AssemblyProduct("VersionOne.ServerConnector")]
[assembly: AssemblyTitle("VersionOne.ServerConnector")]
[assembly: AssemblyDescription("VersionOne ServerConnector Library VersionOne.ServerConnector Release Build")]
[assembly: AssemblyCompany("VersionOne, Inc.")]
[assembly: AssemblyCopyright("Copyright 2013, VersionOne, Inc., Licensed under modified BSD.")]

[assembly: AssemblyConfiguration("Release")]
