// Auto generated by build.sh at Tue Nov  5 21:04:01 UTC 2013
using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyProduct("VersionOne.ServerConnector")]
[assembly: AssemblyTitle("VersionOne ServerConnector Library")]
[assembly: AssemblyDescription("VersionOne ServerConnector Library")]
[assembly: AssemblyCompany("VersionOne, Inc.")]
[assembly: AssemblyCopyright("Copyright 2013, VersionOne, Inc., Licensed under modified BSD.")]
[assembly: AssemblyVersion("1.0.1026")]
[assembly: AssemblyFileVersion("1.0.1026")]

[assembly: AssemblyConfiguration("Release")]
